// <auto-generated />
using System;
using Agregator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Agregator.Migrations.ApplicationStore
{
    [DbContext(typeof(ApplicationStoreContext))]
    [Migration("20211007124427_bool")]
    partial class @bool
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Agregator.Data.AgregatorUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("BankId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClientID")
                        .HasColumnType("char(22)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountryCitizenshipId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("INN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IdentityReady")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("Male")
                        .HasColumnType("bit");

                    b.Property<string>("Middlename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("ProfileReady")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool?>("agreePrivacy")
                        .HasColumnType("bit");

                    b.Property<bool?>("agreeRegFNS")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("CountryCitizenshipId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Agregator.Data.AppUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Agregator.Data.AppUserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Agregator.Data.Applicant", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("row_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActualPlace")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("actualPlace");

                    b.Property<bool>("Agreement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("agreement")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime")
                        .HasColumnName("birthDate");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("birthPlace");

                    b.Property<int?>("CitizenshipId")
                        .HasColumnType("int")
                        .HasColumnName("citizenshipId");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Creator")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("creator");

                    b.Property<string>("DeviceNumber")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("deviceNumber");

                    b.Property<string>("Education")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("education");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("firstName");

                    b.Property<bool>("Hostel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("hostel")
                        .HasDefaultValueSql("0");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("lastName");

                    b.Property<bool>("Male")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("male")
                        .HasDefaultValueSql("1");

                    b.Property<string>("MarriedStatus")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("marriedStatus");

                    b.Property<string>("MiddleName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("middleName");

                    b.Property<int?>("ProfessionId")
                        .HasColumnType("int")
                        .HasColumnName("professionId");

                    b.Property<string>("Skils")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("skils");

                    b.Property<string>("Tools")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("tools");

                    b.Property<string>("Сonfirmation")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("confirmation");

                    b.HasKey("RowId");

                    b.HasIndex("CitizenshipId");

                    b.HasIndex("ProfessionId");

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("Agregator.Data.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BIK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("Agregator.Data.BlobStorage", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("row_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Blob")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<bool>("IsZip")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("RowGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("RowId");

                    b.HasIndex("AppUserId");

                    b.ToTable("BlobStorage");
                });

            modelBuilder.Entity("Agregator.Data.BuildObject", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("row_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("AppId")
                        .HasColumnType("tinyint")
                        .HasColumnName("app_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("created");

                    b.Property<decimal?>("Lat")
                        .HasColumnType("decimal(15,6)")
                        .HasColumnName("lat");

                    b.Property<decimal?>("Lng")
                        .HasColumnType("decimal(15,6)")
                        .HasColumnName("lng");

                    b.Property<string>("Map")
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("map");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime")
                        .HasColumnName("updated");

                    b.HasKey("RowId");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("FK_Objects_idx");

                    b.ToTable("BuildObjects");
                });

            modelBuilder.Entity("Agregator.Data.CMessage", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("row_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid?>("SendFromId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SendToId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .HasColumnType("varchar(8000)");

                    b.HasKey("RowId");

                    b.HasIndex("SendFromId");

                    b.HasIndex("SendToId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Agregator.Data.Contract", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("row_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DocDate")
                        .HasColumnType("date")
                        .HasColumnName("docDate");

                    b.Property<string>("DocNum")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("num");

                    b.Property<string>("DocUri")
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("docUri");

                    b.Property<string>("FNS_uri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fee");

                    b.Property<Guid?>("IssuerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime")
                        .HasColumnName("paidDate");

                    b.Property<string>("RegistreInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("varchar(8000)")
                        .HasColumnName("remark");

                    b.Property<DateTime?>("SignDate")
                        .HasColumnType("datetime")
                        .HasColumnName("signDate");

                    b.Property<string>("SignUri")
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("signUri");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime")
                        .HasColumnName("updated");

                    b.Property<int?>("reestrId")
                        .HasColumnType("int");

                    b.HasKey("RowId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("IssuerId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("Agregator.Data.ContractAttachment", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("row_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Path")
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("path");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(19,2)")
                        .HasColumnName("price");

                    b.Property<decimal?>("Quant")
                        .HasColumnType("decimal(19,2)")
                        .HasColumnName("quant");

                    b.Property<short>("RowNum")
                        .HasColumnType("smallint")
                        .HasColumnName("rowNum");

                    b.Property<string>("Unit")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime")
                        .HasColumnName("updated");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("userId");

                    b.Property<int>("WorkId")
                        .HasColumnType("int");

                    b.Property<string>("app_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("building")
                        .HasColumnType("int");

                    b.Property<int>("floor")
                        .HasColumnType("int");

                    b.Property<Guid>("object_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("object_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("path_string")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("room")
                        .HasColumnType("int");

                    b.Property<int>("section")
                        .HasColumnType("int");

                    b.HasKey("RowId");

                    b.HasIndex("ContractId");

                    b.HasIndex("WorkId");

                    b.ToTable("ContractAttachments");
                });

            modelBuilder.Entity("Agregator.Data.ContractTemplate", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Core")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Templ")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fullNameTempate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameTempate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RowId");

                    b.ToTable("ContractTemplates");
                });

            modelBuilder.Entity("Agregator.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alfa2")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("alfa2");

                    b.Property<string>("Alfa3")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("alfa3");

                    b.Property<string>("CountryName")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FullName")
                        .HasColumnType("varchar(2000)");

                    b.Property<byte?>("IsEaes")
                        .HasColumnType("tinyint")
                        .HasColumnName("IsEAES");

                    b.Property<byte?>("UseProfile")
                        .HasColumnType("tinyint")
                        .HasColumnName("useProfile");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Agregator.Data.DevelopmentPlan", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("row_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid?>("Creator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FactDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PlanDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("Updater")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WhoResponsible")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WhoResponsibleNavigationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RowId");

                    b.HasIndex("ParentId");

                    b.HasIndex("WhoResponsibleNavigationId");

                    b.ToTable("DevelopmentPlan");
                });

            modelBuilder.Entity("Agregator.Data.Enum", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("row_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("enumTypeRowId")
                        .HasColumnType("int")
                        .HasColumnName("enumTypeRowId1");

                    b.Property<string>("name")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("typeId")
                        .HasColumnType("int")
                        .HasColumnName("enumTypeRowId");

                    b.HasKey("RowId");

                    b.HasIndex("enumTypeRowId");

                    b.ToTable("Enums");
                });

            modelBuilder.Entity("Agregator.Data.EnumType", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("row_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .HasColumnType("varchar(100)");

                    b.HasKey("RowId");

                    b.ToTable("EnumTypes");
                });

            modelBuilder.Entity("Agregator.Data.FeedBackStatus", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("row_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime")
                        .HasColumnName("updated");

                    b.HasKey("RowId");

                    b.ToTable("FeedBackStatus");
                });

            modelBuilder.Entity("Agregator.Data.Feedback", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("row_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'1'");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime")
                        .HasColumnName("updated");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<int>("Vacancy")
                        .HasColumnType("int")
                        .HasColumnName("vacancy");

                    b.HasKey("RowId");

                    b.HasIndex("Status")
                        .HasDatabaseName("FK_Status_idx");

                    b.HasIndex("Vacancy")
                        .HasDatabaseName("FK_Vacancy_idx");

                    b.HasIndex("UserId", "Vacancy")
                        .IsUnique()
                        .HasDatabaseName("IX_user_vacancy");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("Agregator.Data.Frecipient", b =>
                {
                    b.Property<int>("number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("BankId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Male")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("appUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("birthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("birthPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("building")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("citizenship")
                        .HasColumnType("int");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("construction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("countryId")
                        .HasColumnType("int");

                    b.Property<string>("district")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("docDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("docNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("docSerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("docTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("expireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("fioName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("house")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("latinFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("latinLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("mgDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("mgDivision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("mgExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("mgMumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mgOrganization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mgSerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("middleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("organization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("postalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("recipientId")
                        .HasColumnType("int");

                    b.Property<string>("regAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regApartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regBuilding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regConstruption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("regCountryId")
                        .HasColumnType("int");

                    b.Property<string>("regDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regHouse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regPostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regSettlement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regStreet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("settlement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("number");

                    b.ToTable("RecipientsView");
                });

            modelBuilder.Entity("Agregator.Data.PersoneAddress", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("row_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("apartment")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("building")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("city")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("construction")
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("countryId")
                        .HasColumnType("int");

                    b.Property<string>("district")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("house")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("postalCode")
                        .HasColumnType("char(6)");

                    b.Property<string>("settlement")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("state")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("street")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("typeName")
                        .HasColumnType("int");

                    b.HasKey("RowId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("countryId");

                    b.ToTable("PersoneAddresses");
                });

            modelBuilder.Entity("Agregator.Data.PersoneDocument", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("row_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("date")
                        .HasColumnType("date");

                    b.Property<string>("division")
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("expireDate")
                        .HasColumnType("date");

                    b.Property<string>("number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("organization")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("serial")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("typeName")
                        .HasColumnType("int");

                    b.HasKey("RowId");

                    b.HasIndex("AppUserId");

                    b.ToTable("PersoneDocuments");
                });

            modelBuilder.Entity("Agregator.Data.PersonePhone", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("row_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("number")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("typeName")
                        .HasColumnType("int");

                    b.HasKey("RowId");

                    b.HasIndex("AppUserId");

                    b.ToTable("PersonePhones");
                });

            modelBuilder.Entity("Agregator.Data.Position", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("row_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("name");

                    b.Property<bool>("RostScope")
                        .HasColumnType("bit")
                        .HasColumnName("rostScope");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime")
                        .HasColumnName("updated");

                    b.HasKey("RowId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("Agregator.Data.Recipient", b =>
                {
                    b.Property<int>("number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("row_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("accountNumber")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("accountStatus")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("agreementNumber")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("birthDate")
                        .HasColumnType("date");

                    b.Property<string>("birthPlace")
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("citizenship")
                        .HasColumnType("int");

                    b.Property<Guid?>("correlationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("firstName")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("lastName")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("latinFirstName")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("latinLastName")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("middleName")
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("recipientId")
                        .HasColumnType("int");

                    b.Property<string>("selfEmployedStatus")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("updated")
                        .HasColumnType("datetime");

                    b.HasKey("number");

                    b.HasIndex("AppUserId");

                    b.ToTable("Recipients");
                });

            modelBuilder.Entity("Agregator.Data.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Agregator.Data.TwilioLog", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("row_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Error")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("error");

                    b.Property<string>("Request")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("request");

                    b.Property<string>("Response")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("response");

                    b.Property<string>("Sid")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sid");

                    b.HasKey("RowId");

                    b.ToTable("TwilioLog");
                });

            modelBuilder.Entity("Agregator.Data.Vacancy", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("row_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("AddressShowMetroOnly")
                        .HasColumnType("bit")
                        .HasColumnName("address_show_metro_only");

                    b.Property<string>("AreaIdValue")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("area_id_value");

                    b.Property<string>("AreaIdView")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("area_id_view");

                    b.Property<string>("BillingTypeIdValue")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("billing_type_id_value");

                    b.Property<string>("BillingTypeIdView")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("billing_type_id_view");

                    b.Property<string>("Code")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("Creator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionTab1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionTab2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionTab3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeySkillsNameValue")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("key_skills_name_value");

                    b.Property<string>("KeySkillsNameView")
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("key_skills_name_view");

                    b.Property<int?>("Position")
                        .HasColumnType("int")
                        .HasColumnName("position");

                    b.Property<string>("SalaryCurrencyValue")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("salary_currency_value");

                    b.Property<string>("SalaryCurrencyView")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("salary_currency_view");

                    b.Property<decimal?>("SalaryFrom")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("salary_from");

                    b.Property<decimal?>("SalaryTo")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("salary_to");

                    b.Property<string>("SpecializationsIdValue")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("specializations_id_value");

                    b.Property<string>("SpecializationsIdView")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("specializations_id_view");

                    b.Property<string>("TypeIdValue")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type_id_value");

                    b.Property<string>("TypeIdView")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type_id_view");

                    b.Property<DateTime?>("Updated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid?>("Updater")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RowId");

                    b.HasIndex("Position")
                        .HasDatabaseName("FK_Vacancies_Positions_idx");

                    b.ToTable("Vacancies");
                });

            modelBuilder.Entity("Agregator.Data.VacancyBuildObjectCt", b =>
                {
                    b.Property<int>("Vacancy")
                        .HasColumnType("int")
                        .HasColumnName("vacancy");

                    b.Property<int>("Object")
                        .HasColumnType("int")
                        .HasColumnName("object");

                    b.HasKey("Vacancy", "Object");

                    b.HasIndex("Object")
                        .HasDatabaseName("FK_Vacancy_Object_CrossTable_Objects_idx");

                    b.HasIndex("Vacancy")
                        .HasDatabaseName("FK_Vacancy_Object_CrossTable_Vacancies_idx");

                    b.ToTable("VacancyObject_CT");
                });

            modelBuilder.Entity("Agregator.Data.Work", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("row_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'0'");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime")
                        .HasColumnName("updated");

                    b.Property<Guid?>("work_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RowId");

                    b.ToTable("Works");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Agregator.Data.AgregatorUser", b =>
                {
                    b.HasOne("Agregator.Data.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId");

                    b.HasOne("Agregator.Data.Country", "CountryCitizenship")
                        .WithMany()
                        .HasForeignKey("CountryCitizenshipId");

                    b.Navigation("Bank");

                    b.Navigation("CountryCitizenship");
                });

            modelBuilder.Entity("Agregator.Data.AppUserRole", b =>
                {
                    b.HasOne("Agregator.Data.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Agregator.Data.AgregatorUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Agregator.Data.AppUserToken", b =>
                {
                    b.HasOne("Agregator.Data.AgregatorUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Agregator.Data.Applicant", b =>
                {
                    b.HasOne("Agregator.Data.Country", "Citizenship")
                        .WithMany()
                        .HasForeignKey("CitizenshipId");

                    b.HasOne("Agregator.Data.Position", "Profession")
                        .WithMany()
                        .HasForeignKey("ProfessionId");

                    b.Navigation("Citizenship");

                    b.Navigation("Profession");
                });

            modelBuilder.Entity("Agregator.Data.BlobStorage", b =>
                {
                    b.HasOne("Agregator.Data.AgregatorUser", "AppUser")
                        .WithMany("BlobsData")
                        .HasForeignKey("AppUserId");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Agregator.Data.CMessage", b =>
                {
                    b.HasOne("Agregator.Data.AgregatorUser", "SendFrom")
                        .WithMany()
                        .HasForeignKey("SendFromId");

                    b.HasOne("Agregator.Data.AgregatorUser", "SendTo")
                        .WithMany()
                        .HasForeignKey("SendToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SendFrom");

                    b.Navigation("SendTo");
                });

            modelBuilder.Entity("Agregator.Data.Contract", b =>
                {
                    b.HasOne("Agregator.Data.AgregatorUser", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("Agregator.Data.AgregatorUser", "Issuer")
                        .WithMany()
                        .HasForeignKey("IssuerId");

                    b.Navigation("Customer");

                    b.Navigation("Issuer");
                });

            modelBuilder.Entity("Agregator.Data.ContractAttachment", b =>
                {
                    b.HasOne("Agregator.Data.Contract", "Contract")
                        .WithMany("ContractAttachments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Agregator.Data.Work", "Work")
                        .WithMany("ContractAttachments")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("Agregator.Data.DevelopmentPlan", b =>
                {
                    b.HasOne("Agregator.Data.DevelopmentPlan", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("Agregator.Data.AgregatorUser", "WhoResponsibleNavigation")
                        .WithMany()
                        .HasForeignKey("WhoResponsibleNavigationId");

                    b.Navigation("Parent");

                    b.Navigation("WhoResponsibleNavigation");
                });

            modelBuilder.Entity("Agregator.Data.Enum", b =>
                {
                    b.HasOne("Agregator.Data.EnumType", "enumType")
                        .WithMany()
                        .HasForeignKey("enumTypeRowId");

                    b.Navigation("enumType");
                });

            modelBuilder.Entity("Agregator.Data.Feedback", b =>
                {
                    b.HasOne("Agregator.Data.FeedBackStatus", "StatusNavigation")
                        .WithMany("Feedbacks")
                        .HasForeignKey("Status")
                        .HasConstraintName("FK_Status")
                        .IsRequired();

                    b.HasOne("Agregator.Data.AgregatorUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Agregator.Data.Vacancy", "VacancyNavigation")
                        .WithMany("Feedbacks")
                        .HasForeignKey("Vacancy")
                        .HasConstraintName("FK_Vacancy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusNavigation");

                    b.Navigation("User");

                    b.Navigation("VacancyNavigation");
                });

            modelBuilder.Entity("Agregator.Data.PersoneAddress", b =>
                {
                    b.HasOne("Agregator.Data.AgregatorUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId");

                    b.HasOne("Agregator.Data.Country", "country")
                        .WithMany()
                        .HasForeignKey("countryId");

                    b.Navigation("AppUser");

                    b.Navigation("country");
                });

            modelBuilder.Entity("Agregator.Data.PersoneDocument", b =>
                {
                    b.HasOne("Agregator.Data.AgregatorUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Agregator.Data.PersonePhone", b =>
                {
                    b.HasOne("Agregator.Data.AgregatorUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Agregator.Data.Recipient", b =>
                {
                    b.HasOne("Agregator.Data.AgregatorUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Agregator.Data.Vacancy", b =>
                {
                    b.HasOne("Agregator.Data.Position", "PositionNavigation")
                        .WithMany("Vacancies")
                        .HasForeignKey("Position")
                        .HasConstraintName("FK_Vacancies_Positions");

                    b.Navigation("PositionNavigation");
                });

            modelBuilder.Entity("Agregator.Data.VacancyBuildObjectCt", b =>
                {
                    b.HasOne("Agregator.Data.BuildObject", "ObjectNavigation")
                        .WithMany("VacancyBuildObjectCts")
                        .HasForeignKey("Object")
                        .HasConstraintName("FK_Vacancy_Object_CrossTable_Objects")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Agregator.Data.Vacancy", "VacancyNavigation")
                        .WithMany("VacancyBuildObjectCts")
                        .HasForeignKey("Vacancy")
                        .HasConstraintName("FK_Vacancy_Object_CrossTable_Vacancies")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjectNavigation");

                    b.Navigation("VacancyNavigation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Agregator.Data.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Agregator.Data.AgregatorUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Agregator.Data.AgregatorUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Agregator.Data.AgregatorUser", b =>
                {
                    b.Navigation("BlobsData");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Agregator.Data.BuildObject", b =>
                {
                    b.Navigation("VacancyBuildObjectCts");
                });

            modelBuilder.Entity("Agregator.Data.Contract", b =>
                {
                    b.Navigation("ContractAttachments");
                });

            modelBuilder.Entity("Agregator.Data.FeedBackStatus", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("Agregator.Data.Position", b =>
                {
                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("Agregator.Data.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Agregator.Data.Vacancy", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("VacancyBuildObjectCts");
                });

            modelBuilder.Entity("Agregator.Data.Work", b =>
                {
                    b.Navigation("ContractAttachments");
                });
#pragma warning restore 612, 618
        }
    }
}
