display_errors = On
error_reporting = E_ALL
log_errors = On

upload_max_filesize  = 100M
post_max_size = 100M
memory_limit = 256M

disable_functions = exec,system,passthru,shell_exec,popen

allow_url_fopen = Off
allow_url_include = Off

extension=gd
extension=zip

[xdebug]
xdebug.mode=off

error_log = /var/www/html/storage/logs/php_errors.log