[supervisord]
nodaemon=true
user=www-data
logfile=/var/www/html/storage/logs/supervisor/supervisord.log
pidfile=/var/www/html/storage/logs/supervisor/supervisord.pid

[program:php-fpm]
user=www-data
command=/usr/local/sbin/php-fpm
autostart=true
autorestart=true

[program:artisan-reverb]
user=www-data
command=php /var/www/html/artisan reverb:start
autostart=true
autorestart=true

[program:artisan-pulse]
user=www-data
command=php /var/www/html/artisan pulse:check
autostart=true
autorestart=true

[program:artisan-queue]
user=www-data
command=php /var/www/html/artisan queue:work
autostart=true
autorestart=true

[program:artisan-schedule]
user=www-data
command=php /var/www/html/artisan schedule:work
autostart=true
autorestart=true